version: "3.8"
name: bazario-docker-compose

services:
  bazario-gateway:
    image: bazario.gateway
    container_name: bazario.gateway
    build:
      context: ..
      dockerfile: ./Bazario.ApiGateway/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - bazario.gateway.redis

  bazario.gateway.redis:
    image: redis:7-alpine
    container_name: bazario.gateway.redis
    ports:
      - "6379:6379"

  bazario-web:
    image: bazario.web
    container_name: bazario.web
    build:
      context: ../Bazario.Web
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"

  bazario-identity-webapi:
    image: bazario.identity.webapi:${DOTNET_BUILD_CONFIGURATION:-release}
    container_name: bazario.identity.webapi
    build:
      context: ..
      dockerfile: ./Bazario.Identity/src/Bazario.Identity.WebAPI/Dockerfile
    ports:
      - "5001:5001"
      - "5002:5002"
    depends_on:
      - bazario-identity-postgres
      - bazario-queue

  bazario-identity-postgres:
    image: postgres:latest
    container_name: bazario.identity.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bazario_identity
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/postgres/identity/data/:/var/lib/postgresql/data
      - ./.containers/postgres/identity/log/:/var/log/postgresql

  bazario-users-webapi:
    image: bazario.users.webapi:${DOTNET_BUILD_CONFIGURATION:-release}
    container_name: bazario.users.webapi
    build:
      context: ..
      dockerfile: ./Bazario.Users/src/Bazario.Users.WebAPI/Dockerfile
    ports:
      - "5003:5003"
      - "5004:5004"
    depends_on:
      - bazario-users-postgres
      - bazario-queue

  bazario-users-postgres:
    image: postgres:latest
    container_name: bazario.users.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bazario_users
    ports:
      - "5433:5432"
    volumes:
      - ./.containers/postgres/users/data/:/var/lib/postgresql/data
      - ./.containers/postgres/users/log/:/var/log/postgresql

  bazario-notification:
    image: bazario.notification:${DOTNET_BUILD_CONFIGURATION:-release}
    container_name: bazario.notification
    build:
      context: ..
      dockerfile: ./Bazario.Notification/src/Dockerfile
    depends_on:
      - bazario-queue

  bazario-moderation:
    image: bazario.moderation
    build:
      context: ..
      dockerfile: Bazario.Moderation/Dockerfile
    container_name: bazario.moderation
    ports:
      - "5009:5009"
      - "5010:5010"
    depends_on:
      - bazario-queue

  bazario-queue:
    image: rabbitmq:management
    container_name: bazario.queue
    hostname: bazario-queue
    volumes:
      - ./.containers/rabbitmq/queue/data/:/var/lib/rabbitmq
      - ./.containers/rabbitmq/queue/log/:/var/log/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  bazario-mailhog:
    image: mailhog/mailhog
    container_name: bazario.mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - ./.containers/mailhog/data/:/data/maildir
